---

- name: Check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- name: main | Execute newrelic java role
  include: "newrelic_java.yml"
  when: newrelic_java_install_agent|default(False) == True

- name: main | Execute newrelic nodejs role
  include: "newrelic_nodejs.yml"
  when: newrelic_nodejs_install_agent|default(False) == True
